* Create a file called Combined2Map with OCC6DIG -> COMBINEDII mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDII)
10 1
11 1
12 2
13 3
14 4
20 5
21 5
22 6
23 7
24 8
25 9
26 6
27 11
30 12
31 12
32 13
33 14
34 15
35 16
36 17
39 18
40 29
41 29
42 20
43 4
44 18
45 18
50 19
51 20
52 21
53 19
54 19
55 19
56 19
59 22
60 23
61 10
62 23
63 23
70 24
71 24
72 24
73 25
74 26
80 27
81 28
82 27
83 26
84 27
85 27
89 27
end
quietly save "`SAVED'Combined2Map", replace
drop _all

