* Create a file called AnzscoCombined1Map with OCC6DIG -> COMBINEDI mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDI)
10 1
11 2
12 12
13 1
14 19
20 4
21 18
22 2
23 7
24 5
25 3
26 2
27 6
30 8
31 8
32 23
33 16
34 10
35 17
36 20
39 20
40 25
41 3
42 24
43 19
44 27
45 25
50 11
51 1
52 11
53 11
54 11
55 11
56 11
59 11
60 22
61 21
62 22
63 22
70 28
71 28
72 28
73 9
74 14
80 15
81 24
82 15
83 26
84 13
85 17
89 15
end
quietly save "`SAVED'AnzscoCombined1Map", replace
drop _all

