* Create a file called AscoCombined2Map with OCCCP -> COMBINEDII mapping.
* This file was generated by make_do.py
*
input byte(OCCCP COMBINEDII)
10 1
11 1
12 3
13 2
20 5
21 7
22 6
23 9
24 8
25 5
25 11
30 18
31 12
32 20
33 4
34 29
39 18
40 10
41 13
42 13
43 15
44 14
45 16
46 17
49 10
50 19
51 21
59 22
60 19
61 19
63 18
70 24
71 24
72 24
73 25
79 26
80 23
81 19
82 23
83 18
90 27
91 28
92 27
99 27
end
quietly save "`SAVED'AscoCombined2Map", replace
drop _all

