* Create a file called CcloCombined1Map with OCC6DIG -> COMBINEDI mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDI)
1 7
2 7
3 3
4 3
5 3
6 5
7 6
8 18
9 8
10 4
11 2
12 1
13 22
14 11
15 11
16 21
17 21
18 22
19 12
20 13
21 13
22 28
23 1
24 9
25 1
26 11
28 9
29 9
30 9
31 10
32 11
33 20
34 20
35 20
36 23
37 7
38 23
39 10
40 23
41 16
42 18
43 16
44 20
45 17
46 20
47 20
48 26
49 28
50 14
51 15
52 27
53 24
54 19
55 24
56 20
57 24
58 25
59 18
60 25
end
quietly save "`SAVED'CcloCombined1Map", replace
drop _all

