import csv

def make_dofile(serverfile, csvfile, dofile, var1, var2):
    with open(dofile, 'w') as f:
        f.write("""* Create a file called %(svr)s with %(v1)s -> %(v2)s mapping.
* This file was generated by make_do.py
*
input byte(%(v1)s %(v2)s inform routine face site decision)
""" % {"svr": serverfile, "v1": var1, "v2": var2})
        with open(csvfile, 'rb') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            reader.next()
            for row in reader:
                    f.write(' '.join([row[n] for n in range(1, 7+1)]))
                    f.write('\n')

        f.write("""end
quietly save "`SAVED'%(svr)s", replace
drop _all

""" % {"svr": serverfile})

# process CSV files downloaded by download_mappings.sh
# 2000/01 <-> 2009/10
make_dofile('Combined2Map', 'tasks_mapped_anzsco_ii.csv', 'anzsco_combinedii.do', 'OCC6DIG', 'COMBINEDII')
make_dofile('AscoCombined2Map', 'tasks_mapped_ascoii_ii.csv', 'ascoii_combinedii.do', 'OCCCP', 'COMBINEDII')

# 1981/82 <-> 2009/10
make_dofile('AnzscoCombined1Map', 'tasks_mapped_anzsco_i.csv', 'anzsco_combinedi.do', 'OCC6DIG', 'COMBINEDI')
make_dofile('CcloCombined1Map', 'tasks_mapped_cclo_i.csv', 'cclo_combinedi.do', 'OCC6DIG', 'COMBINEDI')

import os
os.system("cat *_*.do > mappings.do")
