import csv

def make_dofile(serverfile, csvfile, dofile, var1, var2):
    with open(dofile, 'w') as f:
        f.write("""* Create a file called %(svr)s with %(v1)s -> %(v2)s mapping.
* This file was generated by make_do.py
*
input byte(%(v1)s %(v2)s)
""" % {"svr": serverfile, "v1": var1, "v2": var2})
        with open(csvfile, 'rb') as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            reader.next()
            for row in reader:
                    f.write(' '.join([row[0], row[2]]))
                    f.write('\n')

        f.write("""end
quietly save "`SAVED'%(svr)s", replace
drop _all

""" % {"svr": serverfile})

# process CSV files downloaded by download_mappings.sh
make_dofile('Combined2Map', 'anzsco_combinedii.csv', 'anzsco_combinedii.do', 'OCC6DIG', 'COMBINEDII')
make_dofile('AscoCombined1Map', 'ascoii_combinedii.csv', 'ascoii_combinedii.do', 'OCC6DIG', 'COMBINEDI')
make_dofile('AnzscoCombined1Map', 'anzsco_combinedi.csv', 'anzsco_combinedi.do', 'OCC6DIG', 'COMBINEDI')

import os
os.system("cat *_*.do > mappings.do")

