* Create a file called AnzscoCombined1Map with OCC6DIG -> COMBINEDI mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDI)
10 1
11 2
12 12
13 1
14 19
20 4
21 18
22 2
23 7
24 5
25 3
26 2
27 6
30 8
31 8
32 23
33 16
34 10
35 17
36 20
39 20
40 25
41 3
42 24
43 19
44 27
45 25
50 11
51 1
52 11
53 11
54 11
55 11
56 11
59 11
60 22
61 21
62 22
63 22
70 28
71 28
72 28
73 9
74 14
80 15
81 24
82 15
83 26
84 13
85 17
89 15
end
quietly save "`SAVED'AnzscoCombined1Map", replace
drop _all

* Create a file called Combined2Map with OCC6DIG -> COMBINEDII mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDII)
10 1
11 1
12 2
13 3
14 4
20 5
21 5
22 6
23 7
24 8
25 9
26 6
27 11
30 12
31 12
32 13
33 14
34 15
35 16
36 17
39 18
40 29
41 29
42 20
43 4
44 18
45 18
50 19
51 20
52 21
53 19
54 19
55 19
56 19
59 22
60 23
61 10
62 23
63 23
70 24
71 24
72 24
73 25
74 26
80 27
81 28
82 27
83 26
84 27
85 27
89 27
end
quietly save "`SAVED'Combined2Map", replace
drop _all

* Create a file called AscoCombined2Map with OCC6DIG -> COMBINEDII mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDII)
10 1
11 1
12 3
13 2
20 5
21 7
22 6
23 9
24 8
25 5
25 11
30 18
31 12
32 20
33 4
34 29
39 18
40 10
41 13
42 13
43 15
44 14
45 16
46 17
49 10
50 19
51 21
59 22
60 19
61 19
63 18
70 24
71 24
72 24
73 25
79 26
80 23
81 19
82 23
83 18
90 27
91 28
92 26
99 27
end
quietly save "`SAVED'AscoCombined2Map", replace
drop _all

* Create a file called CcloCombined1Map with OCC6DIG -> COMBINEDI mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDI)
1 7
2 7
3 3
4 3
5 3
6 5
7 6
8 18
9 8
10 4
11 2
12 1
12 8
13 22
14 11
15 11
16 21
17 21
18 22
19 12
20 13
21 13
22 28
23 1
24 9
25 1
26 11
28 9
29 9
30 9
31 10
32 11
33 20
34 20
35 20
36 23
37 7
38 23
39 10
40 23
41 16
42 18
43 16
44 20
45 17
46 20
47 20
48 26
49 28
50 14
51 15
52 27
53 24
54 19
55 24
56 20
57 24
58 25
59 18
60 25
end
quietly save "`SAVED'CcloCombined1Map", replace
drop _all

cd "/Users/acooper/School/polarization/analysis"

* Create a file called AnzscoCombined1Map with OCC6DIG -> COMBINEDI mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDI)
10 1
11 2
12 12
13 1
14 19
20 4
21 18
22 2
23 7
24 5
25 3
26 2
27 6
30 8
31 8
32 23
33 16
34 10
35 17
36 20
39 20
40 25
41 3
42 24
43 19
44 27
45 25
50 11
51 1
52 11
53 11
54 11
55 11
56 11
59 11
60 22
61 21
62 22
63 22
70 28
71 28
72 28
73 9
74 14
80 15
81 24
82 15
83 26
84 13
85 17
89 15
end
quietly save "AnzscoCombined1Map", replace
drop _all

* Create a file called Combined2Map with OCC6DIG -> COMBINEDII mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDII)
10 1
11 1
12 2
13 3
14 4
20 5
21 5
22 6
23 7
24 8
25 9
26 6
27 11
30 12
31 12
32 13
33 14
34 15
35 16
36 17
39 18
40 29
41 29
42 20
43 4
44 18
45 18
50 19
51 20
52 21
53 19
54 19
55 19
56 19
59 22
60 23
61 10
62 23
63 23
70 24
71 24
72 24
73 25
74 26
80 27
81 28
82 27
83 26
84 27
85 27
89 27
end
quietly save "Combined2Map", replace
drop _all

* Create a file called AscoCombined1Map with OCC6DIG -> COMBINEDI mapping.
* This file was generated by make_do.py
*
input byte(OCC6DIG COMBINEDI)
10 1
11 1
12 3
13 2
20 5
21 7
22 6
23 9
24 8
25 5
25 11
30 18
31 12
32 20
33 4
34 29
39 18
40 10
41 13
42 13
43 15
44 14
45 16
46 17
49 10
50 19
51 21
59 22
60 19
61 19
63 18
70 24
71 24
72 24
73 25
79 26
80 23
81 19
82 23
83 18
90 27
91 28
92 26
99 27
end
quietly save "AscoCombined1Map", replace
drop _all

